import React from 'react';
import {  FaLinkedin, FaGithub, FaTelegram } from 'react-icons/fa';
export const links = [
	{
		id: "1",
		link: "https://devjaymovies.netlify.app",
		github: "https://github.com/JOHNADEBA/tmdb",
		title: "Movies",
		tools: "vue js, tmdb",
		technology: "vue",
	},
	{
		id: "2",
		link: "https://devjaytours.netlify.app",
		github: "https://github.com/JOHNADEBA/tours",
		title: "Tours",
		tools: "REACT",
		technology: "react",
	},
	{
		id: "3",
		link: "https://mystripe.netlify.app",
		tools: "REACT",
		technology: "react",
		github: "https://github.com/JOHNADEBA/stripe-ui",
		title: "Stripe UI",
	},
	{
		id: "4",
		link: "https://devjayshoppingcart.netlify.app",
		tools: "REACT",
		technology: "react",
		github: "https://github.com/JOHNADEBA/shoppingcart",
		title: "SHopping Cart",
	},
	{
		id: "5",
		link: "https://myusersreviews.netlify.app",
		tools: "REACT",
		technology: "react",
		github: "https://github.com/JOHNADEBA/users-reviews",
		title: "REVIEWS",
	},
	{
		id: "6",
		link: "https://devjayrandomuser.netlify.app",
		tools: "REACT",
		technology: "react",
		github: "https://github.com/JOHNADEBA/random-user",
		title: "Random User",
	},
	{
		id: "7",
		link: "https://devjayquiz.netlify.app",
		tools: "REACT",
		technology: "react",
		github: "https://github.com/JOHNADEBA/quiz",
		title: "Quiz",
	},
	{
		id: "8",
		link: "https://myjobprofile.netlify.app",
		tools: "REACT",
		technology: "react",
		github: "https://github.com/JOHNADEBA/job-profile",
		title: "Profile",
	},
	{
		id: "9",
		link: "https://devjaypagination.netlify.app",
		tools: "REACT",
		technology: "react",
		github: "https://github.com/JOHNADEBA/pagination",
		title: "Pagination",
	},
	{
		id: "10",
		link: "https://myrestaurantmenu.netlify.app",
		tools: "REACT",
		technology: "react",
		github: "https://github.com/JOHNADEBA/restaurant-menu",
		title: "Restaurant Menu",
	},
	{
		id: "11",
		link: "https://myloremgenerate.netlify.app",
		tools: "REACT",
		technology: "react",
		github: "https://github.com/JOHNADEBA/lorem-generate",
		title: "Lorem Generator",
	},
	{
		id: "12",
		link: "https://devjayoffice.netlify.app",
		tools: "ANGULAR",
		technology: "angular",
		github: "https://github.com/JOHNADEBA/angularSmartAccordion",
		title: "Switch Play",
	},
	{
		id: "13",
		link: "https://jaycocktail.netlify.app",
		tools: "REACT",
		technology: "react",
		github: "https://github.com/JOHNADEBA/cocktailmenu",
		title: "Cocktails Menu",
	},
	{
		id: "14",
		link: "https://myreactjstodo.netlify.app/",
		tools: "REACT",
		github: "https://github.com/JOHNADEBA/React-js-TodoList",
		title: "Simple TodoList",
		technology: "react",
	},
	{
		id: "15",
		link: "https://radio-fm.netlify.app/",
		github: "https://github.com/JOHNADEBA/cloned-radio-station-website",
		title: "Radio Fm",
		tools: "REACT",
		technology: "react",
	},
	{
	    id:'16',
	    link: 'https://thespa.netlify.app/',
	    github:'https://github.com/JOHNADEBA/spa',
	    title: 'Spa Website',
	    tools: 'html',
	    technology: 'react',

	},
	{
		id: "17",
		link: "https://devjayflipcard.netlify.app/",
		tools: "HTML, CSS, JAVASCRIPT",
		technology: "html",
		title: "FlipCard",
		github: "https://github.com/JOHNADEBA/flipcard",
	},
	{
		id: "18",
		link: "https://mycolorpika.netlify.app/",
		github: "https://github.com/JOHNADEBA/12-React-js-projects/blob/master/src/Colors.js",
		title: "Colour Picker",
		tools: "REACT",
		technology: "react",
	},
	{
		id: "19",
		link: "https://robofrenz.netlify.app/",
		tools: "REACT",
		technology: "react",
		title: "Robot Friends",
		github: "https://github.com/JOHNADEBA/Robots-search",
	},
	{
		id: "20",
		link: "https://wordplaygame.netlify.app/",
		tools: "HTML, CSS, JAVASCRIPT",
		technology: "html",
		title: "Word Play",
		github: "https://github.com/JOHNADEBA/Word-Beater",
	},
	{
		id: "21",
		link: "https://tempconvata.netlify.app/",
		tools: "HTML, CSS, JAVASCRIPT",
		technology: "html",
		title: "Temperature Converter",
		github: "https://github.com/JOHNADEBA/Temperature-Converter",
	},
    {
        id:'22',
        link: 'https://rokpepasiszo.netlify.app/',
        tools: 'HTML, CSS, JAVASCRIPT',
        technology: 'html',
        title: 'Rock, Paper, Scissor',
        github: "https://github.com/JOHNADEBA/Rock-Paper-Scissors",
    },
    {
        id:'23',
        link: 'https://keyboardsound.netlify.app/',
        tools: 'HTML, CSS, JAVASCRIPT',
        technology: 'html',
        title: 'Sound Maker',
        github: "https://github.com/JOHNADEBA/music-app",
    },
    {
        id:'24',
        link: 'https://kontactlist.netlify.app/',
        tools: 'HTML, CSS, JAVASCRIPT',
        title: 'Filter ContactList',
        technology: 'html',
        github: "",
    },
    {
        id:'25',
        link: 'https://devjaydigitalclock.netlify.app/',
        tools: 'HTML, CSS, JAVASCRIPT',
        title: 'Digital Clock',
        technology: 'html',
        github: "https://github.com/JOHNADEBA/Digital-Clock",
    },
    {
        id:'26',
        link: 'https://chargebattery.netlify.app/',
        tools: 'HTML, CSS, JAVASCRIPT',
        title: 'Battery Charging',
        technology: 'html',
        github: "https://github.com/JOHNADEBA/Charging-battery",
    },
    {
        id:'27',
        link: 'https://devjayecommerce.netlify.app',
        tools: 'REACT',
        title: 'E-Commerce',
        technology: 'react',
        github: "https://github.com/JOHNADEBA/e-commerce",
    },
];
export const social = [
  {
    id: 1,
    url: 'https://github.com/JOHNADEBA',
    icon: <FaGithub />,
  },
  {
    id: 2,
    url: 'https://telegram.org/drealbigj',
    icon: <FaTelegram />,
  },
  {
    id: 3,
    url: 'https://www.linkedin.com/in/john-adeba-794738117/',
    icon: <FaLinkedin />,
  },
  
];